# POLSCI 3

## Week 5, SANDBOX Social pressure data

In this activity, we are going to practice our approach for comparing treatment and control groups in experiments, using the `difference_in_means()` function from the `estimatr` package.

### The Data

We're going to be using the Social Pressure dataset from Gerber, Green, and Larimer, but with a tweak to how the treatment variable is recorded.

In many datasets with experiments that have more than 2 treatment conditions (e.g., instead of just treatment and control, multiple treatments and control), which treatment condition a person is in is saved as a string. You'll see why in a moment.

In [1]:
#RUN THIS CELL
library(testthat)
library(estimatr) # This loads the estimatr package, where the difference_in_means() function is from.

social <- read.csv('ps3_week5_social_pressure_str.csv')
head(social)

  outcome_voted treat   sex    age g2000 g2002 median_income p2004 democrat
1 0             self    female 46  1     0     52688         1     1
2 1             self    female 38  1     1     37774         1     0
3 1             control male   57  1     0     70230         1     1
4 0             control male   41  1     1     35644         0     0
5 0             control female 35  1     1     46908         1     0
6 0             control male   44  1     1     63693         1     0

Here's what the variables mean:

- Outcome: `outcome_voted`: 1 if that particular person voted, 0 if not.
- `treat` is now a string with the following values:
    - `"control"`: assigned to control group
    - `"civic"`: mail with "do your civic duty" message
    - `"hawthorne"`: mail that says that the voter is being observed
    - `"self"`: mail with own voting history
    - `"neighbors"`: mail with own and neighbors' voting history
- Other Variables:
    - `sex`: 1 female, 0 male
    - `yob`: year of birth
    - `g2000`: voted in 2000 general election
    - `g2002`: voted in 2002 general election
    - `median_income`: median income in the last 12 months in person's neighborhood
    - `p2004`: voted in 2004 primary election
    - `democrat`: registered Democrat

In [2]:
table(social$treat)

    civic   control hawthorne neighbors      self
    20001     99999     20002     20000     20000

In [3]:
# Don't worry about how this code works, just take a look at the results.
data.frame(Condition = c('Control', 'Civic Duty', 'Hawthorne', 'Self', 'Neighbors'),
          `Turnout Rate` = 100*with(social, c(mean(outcome_voted[treat=='control']), mean(outcome_voted[treat=='civic']),
           mean(outcome_voted[treat=='hawthorne']), mean(outcome_voted[treat=='self']), mean(outcome_voted[treat=='neighbors']))))

  Condition  Turnout.Rate
1 Control    30.39030
2 Civic Duty 32.64837
3 Hawthorne  32.98170
4 Self       35.65500
5 Neighbors  39.03000

## Using the `difference_in_means()` function

Let's compute the effect of the Hawthorne mailer.

### Old way to compute the effect of the Hawthorne mailer

In [ ]:
# First, subset to just those assigned to Hawthorne mailer
hawthorne.subset <- subset(social, treat == 'hawthorne')

# Second, subset to the control group
control.subset <- subset(social, treat == 'control')

# Now, take the difference (this is already shorter than what you've learned before)
hawthorne.effect <- mean(hawthorne.subset$outcome_voted) - mean(control.subset$outcome_voted)

hawthorne.effect # Let's see the results.

### New way, using `difference_in_means()`

Here's the generic recipe:

`difference_in_means(outcome.name ~ treatment.name, dataset.name, condition1 = 'control.condition', condition2 = 'treatment.condition')`

You'll replace:
- `outcome.name` with the name of the variable name in the dataset that contains with the outcome
- `treatment.name` with the name of the variable name in the dataset that contains the treatment variable
- `dataset.name` with the name of the dataset
- `'control.condition'` with whatever the *baseline* for comparison is (usually the control group name)
- `'treatment.condition'` with whatever the *treatment* you're trying to estimate the effect of is (one of the treatment group names)

(This is available in the <a href="https://bcourses.berkeley.edu/courses/1550624/pages/r-cheat-sheet-ps-3-spring-26" target="_blank">R Cheat Sheet</a>.)

Let's see this for the effect of the Hawthorne mailer:

In [ ]:
hawth_effect <- difference_in_means(outcome_voted ~ treat, social, condition1 = 'control', condition2 = 'hawthorne')
hawth_effect

In [ ]:
hawth_vs_civic <- difference_in_means(outcome_voted ~ treat, social, condition1 = 'civic', condition2 = 'hawthorne')

hawth_vs_civic # Let's look at what we computed. (Don't change this line.)

In [ ]:
difference_in_means(outcome_voted ~ treat, social, condition1 = 'control', condition2 = 'civic')

In [ ]:
# You can also practice the difference_in_means() function using 
# the social pressure data that does not record treatment as a string variable!

# We'll call this "social2"

# RUN THIS CELL
social2 <- read.csv('ps3_week5_social_pressure.csv')
head(social)